/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package io.services.user;


import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

@SpringBootApplication
public class UserService {

    public static void main(String[] args) {
        // Hooks.onOperatorDebug();
        SpringApplication.run(UserService.class, args);
    }

}