# Istio Gateway name
nameOverride: iozone-gateway
# Istio Gateway spec.
servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
      - "*"
  - port:
      number: 15021
      name: tcp
      protocol: TCP
    hosts:
      - "*"