/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package io.service.user;


import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.EnableAutoConfiguration;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration;
import org.springframework.boot.autoconfigure.jdbc.DataSourceTransactionManagerAutoConfiguration;

@SpringBootApplication
// We exclude DataSourceAutoConfiguration in favor to R2DBC dataSource config.
@EnableAutoConfiguration(exclude = {DataSourceAutoConfiguration.class, DataSourceTransactionManagerAutoConfiguration.class})
public class Api {

    public static void main(String[] args) {
        SpringApplication.run(Api.class, args);
    }

}