server:
  port: 8888
spring:
  application:
    name: configserver
  cloud:
    config:
      server:
        git:
          defaultLabel: main
          refreshRate: 60
          uri: https://github.com/bilelkhalsi/io-services-config