server:
  port: 8888

spring:
  cloud:
    config:
      server:
        git:
          defaultLabel: main
          refreshRate: 60
          uri: file:///${user.home}/workspace/github/io-services-config
