/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package io.zone.user;

import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    @Test public void testAppHasAGreeting() {
        Api classUnderTest = new Api();
        assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }
}
