/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package io.service.user;

import org.junit.jupiter.api.Test;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.test.context.ActiveProfiles;

import static org.junit.jupiter.api.Assertions.assertNotNull;

@SpringBootTest
@ActiveProfiles({"test"})
public class AppTest {

    @Test
    public void testAppHasAGreeting() {
        assertNotNull("app should have a greeting");
    }
}
