version: '3.1'

services:

  postgres:
    image: bitnami/postgresql
    container_name: io_postgres
    restart: always
    volumes:
    - ./init:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432

  postgres_adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
