kind: IstioOperator
apiVersion: install.istio.io/v1alpha1
metadata:
  namespace: istio-system
  name: kind-istiocontrolplane
spec:
  profile: default
  meshConfig:
    accessLogFile: /dev/stdout
  addonComponents:
    grafana:
      enabled: true
    kiali:
      enabled: true
    prometheus:
      enabled: true
  components:
    ingressGateways:
    - name: istio-ingressgateway
      enabled: true
      k8s:
        service:
          ports:
            - name: status-port
              port: 15021
              targetPort: 15021
              nodePort: 31370
            - name: http2
              port: 80
              targetPort: 8080
              nodePort: 31380
            - name: https
              port: 443
              targetPort: 8443
              nodePort: 31390
  values:
    gateways:
      istio-ingressgateway:
        type: NodePort
