# Istio VirtualService spec.
VirtualService:
  hosts:
    - "*"
  gateways:
    - istio-system/iozone-gateway
  http:
    - match:
        - uri:
            prefix: /backlog
      route:
        - destination:
            host: backlog.default.svc.cluster.local
            port:
              number: 80
# No Istio DestinationRule needed.
DestinationRule: null


