server:
  port: 9004
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json
    min-response-size: 1024
  http2:
    enabled: true

spring:
  liquibase:
    change-log: classpath:/db/changelog/changelog-master.xml
    url: jdbc:postgresql://192.168.155.184:30000/iozone
    user: iozone
    password: iozone

  r2dbc:
    url: r2dbc:postgresql://192.168.155.184:30000/iozone
    username: iozone
    password: iozone

  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false

  resources:
    cache:
      period: 31536000
      cachecontrol:
        max-age: 31536000
    chain:
      html-application-cache: true
      enabled: true
      strategy:
        content:
          enabled: true
          paths: /webjars/swagger-ui/**.*

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/auth/realms/iozone
          jwk-set-uri: http://localhost:8080/auth/realms/iozone/protocol/openid-connect/certs

springdoc:
  swagger-ui:
    path: /swagger-ui
  version: '@springdoc.version@'

management:
  endpoint:
    metrics:
      enabled: true

logging:
  level:
    liquibase: DEBUG
    org.springframework.data.r2dbc: DEBUG
