name: ServiceDbMigration - Release
on:
  push:
    branches:
      - main
    paths:
      - service-db-migration/**
jobs:
  release-user-api:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: service-db-migration
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.GHCR_USERNAME }}
          password: ${{ secrets.GHCR_TOKEN }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: bilelkhalsi/service-db-migration:latest
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
