name: Build user-service release docker image
on:
  release:
    types: [published]
jobs:
  release-user-api:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: user-service
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Build with Maven
        run: mvn clean install --no-transfer-progress

      - name: Build Docker image
        run: mvn compile jib:build --no-transfer-progress