name: Build db-migration release docker image
on:
  workflow_dispatch:
  release:
    types: [published]
jobs:
  release-user-api:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./service-db-migration
          file: ./service-db-migration/Dockerfile
          push: true
          tags: |
            ioservices/service-db-migration:${{ github.event.release.tag_name }}
            ioservices/service-db-migration:latest
            ghcr.io/bilelkhalsi/ioservices/service-db-migration:latest

