name: IoServices Maven Release
on: workflow_dispatch
jobs:
  release:
    runs-on: ubuntu-latest
    steps:

      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
          server-id: github

      - name: Configure Git user
        env:
          GIT_EMAIL: ${{ secrets.GH_ACTION_EMAIL }}
          GIT_NAME: ${{ secrets.GH_ACTION_NAME }}
        run: |
          git config user.email "${GIT_EMAIL}"
          git config user.name "${GIT_NAME}"

      - name: Maven release
        run: mvn -B clean release:prepare release:perform --no-transfer-progress
        env:
          GITHUB_TOKEN: ${{ secrets.GH_ACTION_PAT }}
